-- Bootstrap objects required before Docker can push the image.
-- Values are rendered by deploy.sh from .env or exported environment variables.

CREATE DATABASE IF NOT EXISTS IDENTIFIER('__DATABASE__');
USE DATABASE IDENTIFIER('__DATABASE__');

CREATE SCHEMA IF NOT EXISTS IDENTIFIER('__SCHEMA__');
USE SCHEMA IDENTIFIER('__SCHEMA__');

CREATE IMAGE REPOSITORY IF NOT EXISTS IDENTIFIER('__REPOSITORY__');

CREATE COMPUTE POOL IF NOT EXISTS IDENTIFIER('__COMPUTE_POOL__')
  MIN_NODES = 1
  MAX_NODES = 2
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_SUSPEND_SECS = 3600;

DESCRIBE COMPUTE POOL IDENTIFIER('__COMPUTE_POOL__');